name: travel_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_bottom_navigation_bar: ^0.2.1
  cached_network_image: ^2.5.0
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.16.0
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dots_indicator: ^1.0.0
  easy_localization: ^2.1.0
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flare_flutter: ^1.6.2
  flutter_html: ^1.2.0
  flutter_icons: ^1.1.0
  flutter_widget_from_html: ^0.5.1+3
  flutter_polyline_points: ^0.2.4
  geo: ^0.2.4
  google_fonts: ^1.1.2
  google_maps_flutter: ^1.2.0
  google_sign_in: ^4.5.9
  html: ^0.14.0+4
  html_unescape: ^1.0.1+3
  http: ^0.12.2
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  launch_review: ^2.0.0
  line_icons: ^0.2.0
  md2_tab_indicator: ^1.0.2
  package_info: ^0.4.3+4
  provider: ^4.3.3
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  skeleton_text: ^2.0.2
  sliding_up_panel: ^1.0.2
  toast: ^0.1.5
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/translations/
      - assets/images/splash.png